#!/usr/bin/env node
/**
 * Applies Requesterr branding on top of the upstream seerr source tree.
 *
 * Runs at build time (see Dockerfile) so the files tracked in git stay
 * byte-identical to upstream and `git merge upstream/develop` stays clean.
 * Idempotent: safe to run in multiple Docker stages or repeatedly.
 *
 * Environment overrides:
 *   REBRAND_NAME             display name (default: Requesterr)
 *   REBRAND_PUBLIC_LOGO_URL  logo URL embedded in notification emails
 *                            (default: https://requesterr.net/logo_full.svg)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const BRAND = process.env.REBRAND_NAME ?? 'Requesterr';
const LOGO_URL =
  process.env.REBRAND_PUBLIC_LOGO_URL ?? 'https://requesterr.net/logo_full.svg';

const failures = [];
let patched = 0;

// Exact-match replacements. If a pattern is missing and its replacement is
// absent too, upstream has drifted — fail the build rather than ship a
// half-branded image.
const targeted = [
  {
    file: 'server/lib/settings/index.ts',
    from: "applicationTitle: 'Seerr'",
    to: `applicationTitle: '${BRAND}'`,
  },
  {
    file: 'server/lib/settings/index.ts',
    from: "senderName: 'Seerr'",
    to: `senderName: '${BRAND}'`,
  },
  {
    file: 'src/components/PWAHeader/index.tsx',
    from: "applicationTitle = 'Seerr'",
    to: `applicationTitle = '${BRAND}'`,
  },
  {
    file: 'public/site.webmanifest',
    from: '"name": "Seerr"',
    to: `"name": "${BRAND}"`,
  },
  {
    file: 'public/site.webmanifest',
    from: '"short_name": "Seerr"',
    to: `"short_name": "${BRAND}"`,
  },
  {
    file: 'seerr-api.yml',
    from: "title: 'Seerr API'",
    to: `title: '${BRAND} API'`,
  },
  {
    file: 'server/lib/notifications/agents/email.ts',
    from: "'https://raw.githubusercontent.com/seerr-team/seerr/refs/heads/develop/public/logo_full.svg'",
    to: `'${LOGO_URL}'`,
  },
];

for (const { file, from, to } of targeted) {
  const abs = path.join(root, file);
  const content = fs.readFileSync(abs, 'utf8');
  if (content.includes(from)) {
    fs.writeFileSync(abs, content.replaceAll(from, to));
    patched++;
  } else if (!content.includes(to)) {
    failures.push(`${file}: pattern not found: ${from}`);
  }
}

// Brand-name sweep over locale files. "Seerr" is a proper noun and is not
// translated, but agglutinative languages inflect it (Seerrs, Seerriga,
// Seerrrel…), so match the prefix and keep the grammatical suffix. The
// leading \b keeps Overseerr/Jellyseerr (lowercase s) untouched.
const LOCALE_RE = /\bSeerr/g;
const localeDirs = ['src/i18n/locale', 'server/i18n/locale'];
let localeHits = 0;
let localeFiles = 0;
if (!fs.existsSync(path.join(root, localeDirs[0]))) {
  failures.push(`${localeDirs[0]}: locale directory missing — upstream moved it`);
}
for (const dir of localeDirs) {
  const abs = path.join(root, dir);
  if (!fs.existsSync(abs)) continue;
  for (const name of fs.readdirSync(abs)) {
    if (!name.endsWith('.json')) continue;
    const file = path.join(abs, name);
    const content = fs.readFileSync(file, 'utf8');
    const replaced = content.replace(LOCALE_RE, BRAND);
    if (replaced !== content) {
      fs.writeFileSync(file, replaced);
      localeFiles++;
      localeHits += (content.match(LOCALE_RE) ?? []).length;
    }
  }
}

// react-intl falls back to the defaultMessage compiled from the TSX source
// whenever a translation is missing or empty (30+ locale files have empty
// strings), so the source-level brand mentions must be swept too.
// src/utils/plex.ts is excluded: its "Seerr" is a Plex protocol identifier
// (X-Plex-Device-Name) that must stay stable to avoid re-registering the
// device with the media server.
const SRC_SWEEP_EXCLUDE = new Set(['src/utils/plex.ts']);
let srcHits = 0;
let srcFiles = 0;
const sweepSrc = (dir) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    const rel = path.relative(root, abs);
    if (entry.isDirectory()) {
      if (rel !== 'src/i18n/locale') sweepSrc(abs);
      continue;
    }
    if (!/\.(ts|tsx)$/.test(entry.name) || SRC_SWEEP_EXCLUDE.has(rel)) continue;
    const content = fs.readFileSync(abs, 'utf8');
    const replaced = content.replace(/\bSeerr\b/g, BRAND);
    if (replaced !== content) {
      fs.writeFileSync(abs, replaced);
      srcFiles++;
      srcHits += (content.match(/\bSeerr\b/g) ?? []).length;
    }
  }
};
sweepSrc(path.join(root, 'src'));

// Overlay branded assets onto public/ (logos, favicons, PWA icons, splash
// screens — everything generated by branding/generate-assets.mjs).
const overlay = path.join(root, 'branding', 'public');
let assetCount = 0;
if (!fs.existsSync(overlay)) {
  failures.push('branding/public: asset overlay directory missing');
} else {
  for (const name of fs.readdirSync(overlay)) {
    fs.copyFileSync(path.join(overlay, name), path.join(root, 'public', name));
    assetCount++;
  }
  if (assetCount < 10) {
    failures.push(`branding/public: only ${assetCount} assets found — expected the full icon set`);
  }
}

// Fail-closed postcondition: no user-facing "Seerr" may survive the sweep.
// Catches upstream drift (new strings, new inflections) at build time
// instead of shipping a partially branded image.
for (const dir of localeDirs) {
  const abs = path.join(root, dir);
  if (!fs.existsSync(abs)) continue;
  for (const name of fs.readdirSync(abs)) {
    if (!name.endsWith('.json')) continue;
    const content = fs.readFileSync(path.join(abs, name), 'utf8');
    const residual = content.match(/\bSeerr\w*/g);
    if (residual) {
      failures.push(`${dir}/${name}: residual brand strings: ${[...new Set(residual)].join(', ')}`);
    }
  }
}

if (failures.length) {
  console.error(`rebrand: FAILED\n  ${failures.join('\n  ')}`);
  process.exit(1);
}

console.log(
  `rebrand: applied "${BRAND}" — ${patched} targeted patches, ` +
    `${localeHits} locale strings across ${localeFiles} files, ` +
    `${srcHits} defaultMessage strings across ${srcFiles} source files, ` +
    `${assetCount} assets copied`
);
